server:
  port: 8083
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sivasainarasimha/Config-Server.git
          clone-on-start: true
management:
  security:
    enabled=false